# https://fabricmc.net/develop/
minecraft_version=26.1
loader_version=0.18.5
loom_version=1.15-SNAPSHOT
fabric_api_version=0.144.4+26.1

# https://repo.opencollab.dev/main/org/geysermc/geyser/api/maven-metadata.xml
geyser_version=2.9.5-SNAPSHOT
# https://repo.opencollab.dev/main/org/geysermc/floodgate/api/maven-metadata.xml
floodgate_version=2.2.5-SNAPSHOT
common_version=1.10-SNAPSHOT
